#!/bin/bash
''' Script-2 that generated Shared-LCT consensus bed file. It needs the name of the new output folder as an input argument: sh comparison.sh <folder-name> (no-slash) '''
echo \n
# Path requirements
path_out=$@
path_outBED="./Bedtools_Out"
# creates new directory named by user in: sh run_ALL_comparison <folder_name>
mkdir -pv $@
mkdir -pv $path_outBED																					

## Condition-specific LCTs:
# generates bed file with LCT detected only in inflammation
sh ./bedtools.sh $path_outBED
# generates bed file with LCT detected only in tumour
sh ./pat_bedtools.sh $path_outBED
# sorts output bed files and saves them in output path folder
sort -k1,1 -k2,2n $path_outBED/only_tum_LCTs.bed > $@/sorted_only_tum_LCTs.bed
sort -k1,1 -k2,2n $path_outBED/only_inflamed_LCTs.bed > $@/sorted_only_inflamed_LCTs.bed

## Comparison and shared-LCT detection
# detects shared-LCT from both conditions
bedtools intersect -a $@/sorted_only_tum_LCTs.bed -b $@/sorted_only_inflamed_LCTs.bed -s > $@/shared_inflVStum_LCTs.bed	
# sorts shared-LCT bed file		
sort -k1,1 -k2,2n $@/shared_inflVStum_LCTs.bed > $@/final_sorted_inflVStum_LCTs.bed
# merges shared-LCT file: it can be tracked using UCSC (Custom Track option)		
bedtools merge -i $@/final_sorted_inflVStum_LCTs.bed -s > $@/final_file.bed				

## Downstream analysis: Now, one can annotate the shared-LCTs using bedtools intersect and the six first columns of the hg19.bed file (chr, chr coordinates, gene RefSeq accession, score, and strand) generated by UCSC Table:
input_file=$@/final_sorted_inflVStum_LCTs.bed
# sorts annotation file	
sort -k1,1 -k2,2n ./Annotation_hg19/hg19.bed > $@/sorted_hg19.bed	
# intersection of shared-LCT bed file and hg19 annotation file and generates annotation bed file						
bedtools intersect -wb -wa -a $input_file -b $@/sorted_hg19.bed -s -sorted -f 0.8 > $@/annot.bed
# sorts annotated-shared-LCT bed file	
sort -k1,1 -k2,2n $@/annot.bed > $@/annot_sorted.bed							
# merges output file: it can be further tracked using UCSC (Custom Track option)					
bedtools merge -i $@/annot_sorted.bed -s > $@/annot_merged.bed						


